<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/gemini.php';
requireRole(['program_head','dean','admin']);

$teacherId = intval($_GET['teacher_id'] ?? 0);
$periodId = intval($_GET['period_id'] ?? 0);

if (!$teacherId || !$periodId) {
    die("Teacher and period required.");
}

$teacher = $pdo->prepare("SELECT t.*, d.name as dept_name, p.name as prog_name FROM teachers t LEFT JOIN departments d ON t.department_id = d.id LEFT JOIN programs p ON t.program_id = p.id WHERE t.id = ?");
$teacher->execute([$teacherId]);
$teacher = $teacher->fetch();

$period = $pdo->prepare("SELECT * FROM evaluation_periods WHERE id = ?");
$period->execute([$periodId]);
$period = $period->fetch();

$scores = getTeacherScore($teacherId, $periodId);
$summary = getTeacherSummary($teacherId, $periodId);

$evals = $pdo->prepare("SELECT e.*, u.full_name as rater_name FROM evaluations e LEFT JOIN users u ON e.rater_id = u.id WHERE e.teacher_id = ? AND e.evaluation_period_id = ? ORDER BY e.submitted_at DESC");
$evals->execute([$teacherId, $periodId]);
$evaluations = $evals->fetchAll();

auditLog($_SESSION['user_id'], 'EXPORT_PDF', "Exported PDF for teacher $teacherId period $periodId");
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Evaluation Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #bbb; padding: 6px; text-align: left; }
        th { background: #f0f0f0; }
        .summary { margin: 10px 0; }
        .summary td { font-size: 14px; font-weight: bold; }
        .small { font-size: 10px; color: #666; }
        .ai-box { background: #f0f9ff; border: 1px solid #bae6fd; padding: 12px; margin: 10px 0; border-radius: 6px; }
        .ai-box h3 { color: #0369a1; font-size: 13px; margin-top: 0; }
        .ai-box p, .ai-box li { font-size: 11px; line-height: 1.6; }
        .ai-box ul { padding-left: 18px; }
    </style>
</head>
<body>
    <h1>Teacher Evaluation Report</h1>
    <p><strong>Teacher:</strong> <?php echo htmlspecialchars($teacher['full_name']); ?><br>
    <strong>Department:</strong> <?php echo htmlspecialchars($teacher['dept_name'] ?? 'N/A'); ?> | 
    <strong>Program:</strong> <?php echo htmlspecialchars($teacher['prog_name'] ?? 'N/A'); ?><br>
    <strong>Period:</strong> <?php echo htmlspecialchars($period['title']); ?> (<?php echo $period['start_date']; ?> to <?php echo $period['end_date']; ?>)<br>
    <strong>Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?> by <?php echo htmlspecialchars($_SESSION['full_name']); ?></p>

    <h2>Score Summary</h2>
    <table class="summary">
        <tr><td>Composite Score</td><td><?php echo $scores['composite']; ?> / 5.00</td></tr>
        <tr><td>Student Average (50%)</td><td><?php echo $scores['student_avg']; ?> (n=<?php echo $scores['student_count']; ?>)</td></tr>
        <tr><td>Program Head Average (30%)</td><td><?php echo $scores['ph_avg']; ?> (n=<?php echo $scores['ph_count']; ?>)</td></tr>
        <tr><td>Dean Average (20%)</td><td><?php echo $scores['dean_avg']; ?> (n=<?php echo $scores['dean_count']; ?>)</td></tr>
    </table>

    <?php if ($summary): ?>
    <h2>AI-Generated Performance Summary</h2>
    <div class="ai-box">
        <h3>Generated by Gemini Flash AI on <?php echo $summary['generated_at']; ?></h3>
        <?php 
        $md = nl2br(htmlspecialchars($summary['summary_text']));
        $md = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $md);
        echo $md;
        ?>
    </div>
    <?php endif; ?>

    <h2>Detailed Evaluations</h2>
    <table>
        <thead>
            <tr><th>#</th><th>Date</th><th>Role</th><th>Rater</th><th>Clarity</th><th>Engage</th><th>Fair</th><th>Curr</th><th>Assess</th><th>Mentor</th><th>Attend</th><th>Commit</th><th>Qual</th><th>Comments</th></tr>
        </thead>
        <tbody>
        <?php $i=1; foreach ($evaluations as $e): ?>
        <tr>
            <td><?php echo $i++; ?></td>
            <td><?php echo $e['submitted_at']; ?></td>
            <td><?php echo ucfirst($e['rater_role']); ?></td>
            <td><?php echo $e['rater_name'] ?? 'Anonymous'; ?></td>
            <td><?php echo $e['teaching_clarity'] ?? '-'; ?></td>
            <td><?php echo $e['engagement'] ?? '-'; ?></td>
            <td><?php echo $e['fairness'] ?? '-'; ?></td>
            <td><?php echo $e['curriculum'] ?? '-'; ?></td>
            <td><?php echo $e['assessment'] ?? '-'; ?></td>
            <td><?php echo $e['mentoring'] ?? '-'; ?></td>
            <td><?php echo $e['attendance'] ?? '-'; ?></td>
            <td><?php echo $e['commitment'] ?? '-'; ?></td>
            <td><?php echo $e['quality'] ?? '-'; ?></td>
            <td><?php echo htmlspecialchars($e['comments'] ?? ''); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <p class="small">This report is generated from the Teacher Evaluation System. Student responses are kept anonymous.</p>
    <script>window.print();</script>
</body>
</html>
